apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      pod: cloudflared
  template:
    metadata:
      labels:
        pod: cloudflared
    spec:
      serviceAccountName: cloudflared
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        imagePullPolicy: "Always"
        command:
          - cloudflared
          - tunnel
          - --no-autoupdate
          - run
          - 64ecb7e4-55fe-4ab1-a67a-dad9b883fbc5
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-token
              key: tunnelToken
