---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: default
spec:
  encryptedData:
    tunnelToken: AgAniiNKOmdRHCxiKTByqISogYNvQpHk4dnFQVb5CCywwILAVqPH+FTFBI1yxmzBnF7W+AhQrOETzOTlUNP4wsHUOLpQgW2pTmMpoenFr4M3lCXVPcyFqXgf932yLOXlPT01GeN0FS0Tg/0vvNxFYhGOI1uSjhcHBgDmzaXSEkd0/ACIMEmWbFIoo4K5Mi018uP8lUeNvqKfDd3QUXVOcGOtE4qZ0e6ffMF5ZFKBcq/qG8S5tEk402qz64JJsvPp6TwZxRO9Ifz8vauO3j0ZrItKUXkn5HCqr2xQxAgYBpUnmAyc17Jzax1Fo2YMo2u0pfO4E1k8zgoq8l+PJBsWraYKPrVLL6sPxT+3kKnAV+RNFvjOQ7i9MXh35T4k3nKQVGUqT9+4E8NWZkx6DlT//ngrnvrXgWZLOp6p1EpiTwIQc1mQ/hUSjJL2Ndy1HpAXntzM7aGozoD28nL5SBQEAVnF5ksPFnQH6tTkyZgTZQq0hT9lcpz9Js7nZRdWSboRbK3eMPMIeej7UP2+hH+4OIqjQXcbrhAwMbRd1E27qDm97EEe6ykcufPmqrTc2qSDWggMqudYelEiIJ1lBbnRG2r5B+LFkHx18QiIhtwseq3TWMXKFE8A7YPolXI1m9Mlysu0M1vVfr9H1ZtQ+AGxyCSTfQcRHMpLHKTpuY9p+qZKxJmObqEISuqCPmWfjkjrZ1DIS6XtDpbMNm4BAa7xW8vYltvPXI1lXcxoljALvRVJDqVzizA=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: default
