---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: default
spec:
  encryptedData:
    tunnelToken: AgCgy9dWAlqgFqRl1RVyQtnTUqQWeV8FgUytyAmKKyStgXi0fTHzRi4vBikbw3gZvrQ0ldA88M8HqZba9vH2DqI3Oo2wR0A/SdlS+ehKyvd9qKQ+3aoFXG/yKSlIJyfODYwxEkRg5LE6TXgFL+o/f44zsZ22Zg1UWmLtTwDW2cr8gTr0jZkv7UaZFRj0yyZyqXSIhz9XhmYfmLkewr5jSMeC+Ebd51IcJQNq7I11v/CoXS+KSTEZgYcFXRRakqjdZzBlXSmbmika075srfXFC5lO31NxbPGL7kYa6xp0mqR57q6n6DGjDHkabJP88wSpupi/IX8/M6Vz950QZDBSXVEtyRCc2IjAW4vwpyjkfO4bBF1YSChZSMiLAGIEeUQnGk4LbaaV0Q9xxnY6wJkCZ/mfs6Ne3voV5nr7cJM8oswtM+OTrKoR24L6+ZtA4Cac+BQutrqNagXB8A7kAt8VXxkqoi2kb7Z7drYQibiVZpBml6ncsQf1u8gdvM7IYFBe1l6bnd/clA7ZJK09f9//X4gsAvat4KAWkLbcpdzMe0vdU5PMC8/p+w5AB1qLAk2ME39Qesv10ggGZDOZr877rFOTkn8ZLSpK3QmDqPwI1wOpURqefrnD8EmYhqzUChb0u82jX2r/0U9Vi39IDZyzO+8iJM+t2uBtlNI7HJq7o+D/lxME3d9FiklydakYd3f29jpeevxlNT1M08TZZiDRwbqiwv4+WygkcsRYMqqJdSYmhxaIRC2qo8ZS18f5vBjT4gMVNBoEZSGyWvEqkvon08OrAYwNh+EOeoVwCpS3GUjOqbZutXrkObxOc3aDHjG+bjVgI0yebCqKLjmn9m5HOs5l6ooCf4fx/aqOJ/2aeNoOJOTKWFJRVWYnI18=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: default
