---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: default
spec:
  encryptedData:
    tunnelToken: AgB3OKLoy5RnxpScfjM7xUrbN2gUPUCtl6H1FzJAT6I3D3Jn5Ax+hzWYIDM4sw5mG3zv3c17+c8gJqVZvC8zjDDRWEipC1NJnLD4w1XgJfvFbJpomxfgbcM3pVqWt+VLlWAHPDpCLgXeOg4ondA6TuAtvlgs7P0LjyOju4+c0BBNacJ100biun1gNVMvzFX1pO5m6g3x8WAPYUuZN+NkZ0wFJ6wMzoNX7Rw9Vfbp2ZkXrXhWiJKw+j+h5pysMh724q7wLXUOfJxRiIK24LYRZpnMBIBgB4gv9NOOCS0hr/JQzI1IIDwP8r1nqmoLyVsKVJo2zn4/Dz8OLCDKmYCFiNgGLOUmPWat3y751KOy5apLGSMLCJEG1ugcdS0a8VWw0MiyXWcTSqfB+KvW/OJlPfHYoNMuUD7vUowDdPN/DOXb92p6Qa5EFNlnKZMJYKXvcDqvi6xN5ulmBD1Uu8CwRu3moXg8VygQcXFtN6SkQ9L+KBwcPX2YN04Gfz2EFoJ5Bdbs+NXAd+Rt6OpSn6ACyquANyUlDeU4DaBgkKnNfsaFYHFZEZdrUQxbH2/td5IPuIIPePGsB/iUwaHsjwwNDhN3A6dt01Katjc7wRMybkAaFRyf4mnClZOm4MFw8GCp/NXXqjPtim8eeL+okKYC/6Es7BXv6xeey9TQhzgaqSS2OFeTMFC1RfA4+KfK3m4gC5nSWx0b0vQtYZD9cTrmbdjvZ+kfcrMPml9mpcXSF4mBopDKCkwJ/3cuea9uS0UEeIUOnpUJsToOM+A1uyLHiuzw1cdejkitsjIR4v2XiYk5V9TyHit88xryKDVcvtlP69SO+bWCNku/9P/eqMykMREtN324bocAiwA/z5HajVsOWtMIEMZ1MAfZTHUWYDDfCgyWH3QjVRuEWPUBYWSHnAaPrdc1b9agOhEOy6aXGxNrlVHrzd/SKcGW
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: default
