---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: default
spec:
  encryptedData:
    tunnelToken: AgAE3njXs6SdKBa5v+2+uUhyhxipIJo9Zr50TyoD+rX843R+34/IcbtzHKD4T1XIdbcfk4wpcK2NnSVprB8yI93o+hH7O2XeIRVNqkyyJcgLWeJCbH0u1Mpchy1ljwjC8E7+PuG/jcwVrrvpX2j9j2SN/bWotCJl4BiIJOqx+Ynrcc39/m6Qg7PqU/ZIN9LerV35d8retJYq8W3B7ySykQ7176lG4Ou/AQxb8fFldFExOcKLJ5tBAIhsFuR8MlIDN+FeiM9Ys7TPdhXtekbPfhcV78QuQ+kySZq+BT+DtwN+Pg49TqOP3HSOR+X10ZfgIrFsL8eQyVClS1qy2bBrh31ghfhaneC1VhyCTs3jXHJBIryiUGYzJCj65Jpn4FxYjLdBzvuVoZdwK8KWoRVD5q8I+GcQCtzxRnFzOgCM0JVFVzDUNDzoKWsLqM+ymi1tEZ+l42/keyu7zwhwSkCxqqNXHB1bX5caenPHVr7Wcdv9poDIRfrm3v29EejdJoz3zWw41hfzaoH/PD0INmk0htVzCXDlZFv+aX9pqRbC5kCXr5bKd07IwiWgxEirZrd5WJ9MYGmYEdEnFbH04ECdd89z4iYC1wM7eU779Gjzm7adM/0AlqY/HfSv6aUmSCgFu8ZBXC/JeIZGhVyljt+Hr6L2X0peYUIKXmGWweRAd9aJXTZu2a9ay0JugvPKXF8vgU+T49yXrtRps2zESbsGgKu8a4+DM/sHGRemsLIk7QkvH5gxZ23/7L60auBqacRYgGl6S6l1U9MCL1Gb9sjDgHqi3oBmRKOCc2dqYY8cZHONHXFs17or+/R/lEp/QFSyGzRZVXd/rAQNJ6eGw0h40Nt+XwKMtdFQFo3g0eojCCzoS/n8wUaXFHB0dxoRMmCLbKoxAt71kUeJ9u0DhHdpzci5KQy/kfguCs50fyuIvEo1wpXRfq8z+JDIyPBM1dVO54+sW277W50EvcUJnA0skZZDp5z4NjNMTZjanp2zRWe2ESCntsxnPyWZh73D5aWYdH4=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: default
