---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: default
spec:
  encryptedData:
    tunnelToken: AgCXnqxb4RmgihIdV8BtPWiu/dnoUbg5JkdxKKCMBgGvZR0HbpHGdGGdy+yMQUQpbUNJIvlvpMgi0R0bh9x5xEJ9jGkjZ9emILSSzskT9bN4be5nifmbgMGNM6cpb9hwpLyZXnUSJgOQNxg6SNjFULSPsOn+bOLpBFs5S/asrAfrHR5nGwllqNusK4jdrTYNcvcT2hFUmstS7+D9odZGkqUo+V+benR48J+O/wIGIaq2x7DpDwlgnljc8liTTYo9dmxShgcdw+hTz7mwg+0q4zDeQxc9mTUYbfVzZbQwhxxMY5KbusTXVzQ2h7gCfAp16/7MypPs3MBsZ5BMIUj/4SveXQw20vRVBvwbwRzYnalrxEb1/m8CtnTz2EujtTArqicOrGMF+s1ju7CJt5cFUMa52uBI+PNAywRe9xX2IBpA3WBx6xlk0wcM1xRGbmqLpRMHfigh/jS4fgzgjcchbErnypyuuKBo1MjeUKZnCGfHQW15wGfgT/YPjmLQR+qlh2VTI8iVfLfGHy33PX4GDe6H0sJ9r6g5QV26YRFxYTEhUVdLr2G79jfDb1o9D/UD3PEFyi/3cF6/8zTF7N5/ANY335BWv7qIpEE2vv82UjECVMe4VZsGx0WOdk6csZdIx7LDVn+lMOxojWooW2sL7ALVMMciZ5XJBtLyc8G0G7h8weuBTzeUWSByf3OJ596yvWEjAopThZeTo00KvKPE4L65v0vxXu4iwOVOu3a3MZUpBeCWHxsbfA4U1df47KAx5CAKOrBV8l3PVMI8W590UJfP66lETFfFscIJT7EPe96gTJzTBrQV6TyXAD9PONc4c/5Tt7Y/iA2F94XWHsl49Z3MONdFh77Zcf5IRl4K95z4MHULCVojRjbPttA=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: default
