---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: synology-csi-chart
  namespace: kube-system
spec:
  interval: 1h
  url: https://christian-schlichtherle.github.io/synology-csi-chart
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: '2.17.*'
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      interval: 5m
  releaseName: sealed-secrets
  values:
    replicaCount: 2