---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: default
spec:
  encryptedData:
    tunnelToken: AgDMF8pFm7To4/Jvf9YvYOtwr9DmlNDsnZ2mPZ9DBweSkE5besSMck7MtPEJXgUhH1/nTbi7k45MMl67hztTcUyQPPpZH9Fr4wSRxlNWielZfKD1qG4z9aTtvDooA85Zpn7PHrhf7xs0YYXWqIl4v9sCsvrXUONQmuGWRcGjD8+PfgRQIPfcO5JOhafUOJLVX4UEeNzcIakkIG6+1vO1dGmM6P5IC4ebDN/CtATxILh6ewiKEEkEHZeLyvq4aCqzkEQ+9/gRWQ3pdq4c61ZptTfPq+gwGH6UqSNyYFNy1FwJKhnQKLulm+2NLOTQ0nSccilWAcIvCJlzFfZ8kCFqMv26UXseK6QfmyX9IJEh+tiW6RDJACBEwhOCZZiWgW5BZVldjQoSuw19bjyxXzHD5mXnUifcMi7+rsKvG0SZM0NRkb/00PuQWje3Xr+fVppbFiN1KFXTX4Ooa6K91x6pkQ0HsoXLQEODWLpNQg4BdI4hJsXflrzVwvFanUkgPfHBc2BkwpBdget1dznF6H+V9FSelLAI7SvIWd2wwjBkEG6nVOionYQQHZ0hTABGZTfGYZiJShNUtQRI+Riu6tF9DjzVp1CPuHsiprWZriVMxob3MmjG4JroV/qN0rf5XWZi1s4MdwhB13VKt3U94h1u9ZlkPhbNd+nlN9kZsd6H13M2XaSVo3f52Lm4jI7MA9yx419iFojO1GR2QUCY+Z9SNhwVZYjxSDXLpcRz9VJSfMZ42MJwYE1YT9Io00mD3pSsXDTakpG/6vJ7XhujwmqH+RJ9qEXa6TAauADTPsmkHivB26xk/lBG/uON2dbaK96+HU93ZXwxQ3GOLb+1aDfQyEapDd6BMRbBGwu/NpZ8RwRrx0Ln86UttzM6M0PPoV5nHf7EmXdSilIn7O3QJGcTcWXYC3eE82OB8wxNdP7YQj329etMseTQyWwUEUMK0f4Oy1Sb+McWeU0rUqw5uZ8RJBgM6kBQ2mtRy3vC2sKrOEpjBhpfocot2ZwgnVBm0g3xBmNZ
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: default
    type: Opaque
