---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflared
  namespace: default
spec:
  interval: 5m
  path: "./manifest"
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
