---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudflared
  namespace: default
spec:
  interval: 1h
  url: https://cloudflare.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: default
spec:
  interval: 5m
  chartRef:
    kind: HelmRepository
    name: cloudflared
    namespace: default
  valuesFrom:
    - kind: Secret
      name: cloudflare-token
      valuesKey: tunnel_token
      targetPath: cloudflare.tunnel_token