---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudflared
  namespace: default
spec:
  interval: 1h
  url: https://cloudflare.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: cloudflare-tunnel-remote
  namespace: default
spec:
  interval: 5m0s
  chart: cloudflare-tunnel-remote
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: cloudflared
  version: '5.*'
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: default
spec:
  interval: 5m
  chartRef:
    kind: HelmChart
    name: cloudflare-tunnel-remote
    namespace: default
  valuesFrom:
    - kind: Secret
      name: cloudflare-token
      valuesKey: tunnel_token
      targetPath: cloudflare.tunnel_token