---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: default
spec:
  encryptedData:
    tunnel_token: AgA3W9sXgjcLdtXtj7tEOeR1+g/XBc8rhDBlXMmlMdApTgwNtnH9eeWmQJUeR8kC7IOje/rfGNpeKO5nlsln64ulUzjtY7JB5N802MRhy8K6Q9bJndF1a+14RBWmm8b1BDhzkOeTTQ0QH/igf7nyb0kGVUCiIUeB5bQ17aZjJE6yoMb+r9APHeMNEAq7Ury5YFsfUFimhfvqUEtsraDMVygOilFXkCp+wzW2Dgj4Bh0ip358DJdg08auop7RiZ89FOvE5aN8W1kOQJ82ta0psJbgF67H99zjJ+gbKugzYftjcD89lWlX2h3A4hH+Gp1R860UNklsisfLd4sC4dRnVeioxAdCdcb/Sr8PK2g2KcrOo9zwmHysh9gcwG1bIN+eePWinOSaRhp6KrxrP78hAqQPJCUOsWz9OwAwbadHEGjjp/hOtLecbKHIleJsW2h3y3omDDIQEh1qUe7NqeeryDFeCklaLO6+uz2B7QvOwFhWxCFlKXyvBNXH4ehz+BVoGiY/BanxneRXRxHG3tBFLvOOgtS8yMyhmqpolnVsB3548eAOHCjxKDehE5wJRjoa6qzt2ZHxmioXegv9semVAE+zfIFWblohIqen3XB8uz15aj3ZgvjDC0PgMOUwnKtYZR4O2c9FOdFcsRTQvn75fXch7di18O0EUhmb6rwsMT+4znsHNwNZIIyNY/jpzK/WGnTpYYTJY4zOWOqX6ePO7hP9oP37Fg8QbAA9lPpDEJsV53bM8S87xgYciLxNxt4Z5IOAWSm6IpcrHxKv2xfD/Eu4LzSh//DdLfSZ1qv+3Ip2wnWhgaZitw7Or+tRLZAVtWTeHBiFmEnjJ3hbli/7sk1ejCliqraRwQoHsWyDBFuc63cfcghgyU3U48c=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: default
    type: Opaque
