---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: default
spec:
  encryptedData:
    tunnel_token: AgB+bEzHoCNbg6YHTdMQJaOx9Jb2nBDPgUX02xrkm+csPzOriM21rm0BImqYBxZj1BMnsc1PvRUVSYfsJ+12RVTPPKqugClmvCSnVpSLnG+rOPuHHHPeo83HwZ8iX1SQIaH+pYdBUI+lAh44HOYTkKBB2iGYQXs7GduOYo0IftmMTt+Wxc2/rhvTMj4p5VboQ1WLtM6Cg7jkYEpX8bObWOm0JcUvckguHF97t+7kc14/l4f/4QKHn7AfySw9Aqy+luAF3bY1sDYWHfp/IiZ8Sr/7CFGE+LP1Mc12AXRHDKaRl5S7gTxcoZLgBYEvYFVv9QksicRWH8/hwvMKTC++dzlfh4Ma5k5Ga6Py6KJfocQpnS6fQnxlZ7YfWobmanc3sACGc5+xbVqnsx8m3q26GYzE6Q6zTg32ce43Fqp2V1m+4WRmKkir3V3PMBeR+uyab7HkhFBK00I+8KjKg3rM3/2Z0vnZ/L69UbhwFwkoDGNW2InnDSPvD0UJl3vS9xX0p2vD7n0J0aO+f1i3WrI+XfXpRexYSBTNhii3gklJTr76QkRLYSVSj718QEug+VqDRaSw1UIwcHqw5Ff290kRgg0Fw/kZy53U+4on0spmISpDNn4vPDdsyIFqZSzNPV8wNUv4AnPyr3YhPHjkmma8Y/RO7Sm8+EJ/l3DW398deG3MtgjElKLGAZ09CSZQ1MojySAq/xHIgMaI8oKxwFh3LCbipC7Lm1QTHLkNu759oYwAhy95SaCC
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: default
    type: Opaque
