---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: default
spec:
  encryptedData:
    tunnel_token: AgBnj35+Ya58Is6eWxA34ZhK+CzSy7Rx42e1+VIRJxVRniZhay6Ss+yH0HiIDPSQB+/kqsCLkbu6aLIenwkgK85A3GeXWFhfi4T//O4nytKSWgCU7kPAF8n6Got17fd+u0dH4DR7PeF1etOeuI3Q/ZlMyJ/yD6WookTIetDP8S6eB4yv5L5KU68CEB06LDr1AGYU1zFtmG/4nSoUEP4wWlLz+Niw0+kvqFnm7xzMwrzBp0zr2UaR874YpfTXSmSrBpZwVl3hkw1bO9Mr3PAGKQeLNYkK2oYEBbLfHt3rFVLkAYV908kcYako23PrwjYMgPLYaII+Yd9y4ALh9s1RtHPGsqGlkOY0LroYUJgDvwA6KW/k6G3n/yLsummQTCvy3OVcX5QrEs8nRqLIlGf3m/rc+7lDkem0FSg+ghe//q8b43PIuL+1DsZlaMcOTF2L1qZroWhy+qQY7wRt2EIFe4bDMrR99EBynV4t8KJxDpgjRCN+/2c2udgYkSk6nFq5qz6e+Xq+F+/BqcQ9VvHTZxOdR43BahkXeEUc4jUaBKqb5g6aBv3P0zpqTIN18xK60Z+0IpvkxNTWm+3TzzVJHC3eyBj+N/RvF48WcmnmWZG1gq+F5I1NPqI+lroLIlIMJw61tNmemnSpm2n74sRVe5cDnn1croofZYOQR8m1BFhgEWU/KbAXsG9Q8vkLCA8toAHI/Yt4K76C6N9SnTBRjoxZGz5c3EyoqF0Bmx86H+oii/+MN7L/eVYABqQMyzhnkGN1QKck9FRe+P7yaCpwvo/8QEZEM11fW9Jk8b8R1paTnuHdiZE9s3Mi9grGWPsM/QHcUP6so4NjUFX12cFCWOj66afrd8qUL7S63Ftqe4XLrLhqz/xAU7x3oN0=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: default
    type: Opaque
