---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: default
spec:
  encryptedData:
    tunnel_token: AgCv3KROfMNgvIZdZtb4AXn+05ZcalysQpCGT2g8v7RLe8Zf/gwKIBEVIOdex8LTbPLKrJqkIc9UUAbUZEGW82BIuR5Sgc8UWylH6dUaBJ7dLPAf0qzSSysX2Y5h390TbzXfu4ZF1FfZLS61Z/pBO6hgW6kiWVmu3WjLZGzF+jJHSYDLkp2XNkklB8N8+W9z/7v6swSksmXLtHMtVk1VqZ5Cau0d/bBdS37Oh+FGmcMbA79jyPhzlRxwpZXiIWV729aEvn73Dx5iQkgAWoXs8uOyrlR7x3Iu3pMp9Ks9Db/B9vqMc3C0ZAgzcYADr6NeYp/DklJqZHRrOFi0eiSWQv4MjHKVMfrhzVIK8tHUYNr7d8ZgbasUhJ16uXiTGPgm55ht1UpMacCUTaeuptVJzD28CpVLshU5t5gJiTG2DaSlT4FhT8EfuojAAYX06GXXojTSANUnE9vsO9MyXfW9h6Xn3aqRWox1j+P+9zo7Tta6QtQBQ0/B5qUlRts7lWxJlrPyCoENw7E6k/RfAmLEWe2r/X9SLP8eAEI+DTqmUSWabTQsNP62YVRkSbjdlRkugZLmF5FxPkMvQr6VX41lxQFM4CKDkY4xxC1eiAoy2Vwzo71pVkm00/gl42fHns6XcxYzJHAhiaNCGAN9fUplKPnIZMX0CEVmo4m4WnqNvkDtqSXw6jj2M03UU0TcRx3FSKutw58QhiWNseqhcVPTxes3yHbaZ4F7o9/FOT0OXjsyBfcc7Px9bcoXle83LvURT6zUgLTmgMBWHMg6kRfBi8+6MKnT+3/R19Sw7fGUritF5Blfqcs4ekDjU3gwRfQWfT4QqlHHUaEYab9kI/UzpkhMqrSIcUUbcqeVBBRdqOWHT8SWgb1BtL2hGVs=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: default
    type: Opaque
